name: gl-color-palette-generator
recipe: wordpress
config:
  php: '8.3'
  ssl: true
  xdebug: true
  config:
    php: php.ini
  ServerName: gl-color-palette.lndo.site
  database: mysql:8.0
  webroot: .

services:
  appserver:
    config:
      php: php.ini
    composer:
      phpunit/phpunit: '*'
    build:
      - composer install
    run_as_root:
      - touch /tmp/xdebug.log && chmod 666 /tmp/xdebug.log
    overrides:
      environment:
        XDEBUG_MODE: 'debug,develop,trace,coverage'
        XDEBUG_CONFIG: 'client_host=host.docker.internal client_port=9003 log=/tmp/xdebug.log'
        WP_TESTS_DIR: /app/wordpress-phpunit
        WP_CORE_DIR: /app/wordpress/
        TEST_DB_NAME: wordpress_test
        TEST_DB_USER: wordpress
        TEST_DB_PASS: wordpress
        TEST_DB_HOST: database
        SIMPLETEST_BASE_URL: 'https://gl-color-palette.lndo.site/'
        BROWSERTEST_OUTPUT_DIRECTORY: /app/sites/simpletest/browser_output

  database:
    type: mysql
    healthcheck: mysql -uroot --silent --execute "SHOW DATABASES;"

tooling:
  composer:
    service: appserver
  setup-wp-tests:
    service: appserver
    description: Set up WordPress test environment
    cmd: bash /app/wp-content/plugins/gl-color-palette-generator/bin/install-wp-tests.sh wordpress_test wordpress wordpress database latest true
  test:
    service: appserver
    description: Run plugin tests
    cmd: |
      cd /app/wp-content/plugins/gl-color-palette-generator && \
      composer dump-autoload && \
      if [ "$LANDO_TEST_GROUP" = "wp-mock" ]; then
        vendor/bin/phpunit --group wp-mock
      else
        vendor/bin/phpunit --exclude-group wp-mock
      fi
  test:wp-mock:
    service: appserver
    description: Run wp-mock tests only
    cmd: |
      cd /app/wp-content/plugins/gl-color-palette-generator && \
      composer dump-autoload && \
      vendor/bin/phpunit --group wp-mock
  test:wp:
    service: appserver
    description: Run WordPress integration tests
    cmd: |
      cd /app/wp-content/plugins/gl-color-palette-generator && \
      composer dump-autoload && \
      vendor/bin/phpunit --exclude-group wp-mock
  test:coverage:
    service: appserver
    description: Generate code coverage report
    cmd: cd /app/wp-content/plugins/gl-color-palette-generator && \
      composer dump-autoload && \
      vendor/bin/phpunit --coverage-html ./coverage
  test:unit:
    service: appserver
    description: Run unit tests
    cmd: |
      cd /app/wp-content/plugins/gl-color-palette-generator && \
      vendor/bin/phpunit --testsuite unit
  test:mock:
    service: appserver
    description: Run WP Mock tests
    cmd: |
      cd /app/wp-content/plugins/gl-color-palette-generator && \
      vendor/bin/phpunit --testsuite wp-mock
  test:api:
    service: appserver
    description: Run API tests
    cmd: |
      cd /app/wp-content/plugins/gl-color-palette-generator && \
      vendor/bin/phpunit --testsuite api
  test:core:
    service: appserver
    description: Run core tests
    cmd: |
      cd /app/wp-content/plugins/gl-color-palette-generator && \
      vendor/bin/phpunit --testsuite core
  test:admin:
    service: appserver
    description: Run admin tests
    cmd: |
      cd /app/wp-content/plugins/gl-color-palette-generator && \
      vendor/bin/phpunit --testsuite admin
  test:providers:
    service: appserver
    description: Run provider tests
    cmd: |
      cd /app/wp-content/plugins/gl-color-palette-generator && \
      vendor/bin/phpunit --testsuite providers
