name: gl-color-palette-generator
recipe: wordpress
config:
  php: '8.1'
  ssl: true
  xdebug: true
  config:
    php: php.ini
  ServerName: gl-color-palette-generator.lndo.site
  database: mysql:8.0
  webroot: .

services:
  appserver:
    config:
      php: php.ini
    build_as_root:
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    build:
      - composer install
    run_as_root:
      - touch /tmp/xdebug.log && chmod 666 /tmp/xdebug.log
    overrides:
      environment:
        XDEBUG_MODE: 'debug,develop,trace'
        XDEBUG_CONFIG: 'client_host=host.docker.internal client_port=9003 log=/tmp/xdebug.log'
        WP_TESTS_DIR: /app/wordpress-phpunit
        WP_CORE_DIR: /app/wordpress/
        TEST_DB_NAME: wordpress_test
        TEST_DB_USER: wordpress
        TEST_DB_PASS: wordpress
        TEST_DB_HOST: database
        SIMPLETEST_BASE_URL: 'https://gl-color-palette-generator.lndo.site/'
        BROWSERTEST_OUTPUT_DIRECTORY: /app/sites/simpletest/browser_output

  database:
    type: mysql
    healthcheck: mysql -uroot --silent --execute "SHOW DATABASES;"

  mailhog:
    type: mailhog
    hogfrom:
      - appserver

  pma:
    type: phpmyadmin
    hosts:
      - database

tooling:
  setup-wp-tests:
    service: appserver
    description: Set up WordPress test environment
    cmd: bash bin/install-wp-tests.sh wordpress_test wordpress wordpress database latest true

  test:
    service: appserver
    description: Run all tests
    cmd: bin/test.sh --all
    env:
      - WP_ROOT=/app

  test:unit:
    service: appserver
    description: Run unit tests (providers, api, admin)
    cmd: bin/test.sh --unit
    env:
      - WP_ROOT=/app

  test:mock:
    service: appserver
    description: Run WP Mock tests
    cmd: bin/test.sh --mock
    env:
      - WP_ROOT=/app

  test:integration:
    service: appserver
    description: Run integration tests
    cmd: bin/test.sh --integration
    env:
      - WP_ROOT=/app

  test:providers:
    service: appserver
    description: Run provider tests
    cmd: bin/test.sh --providers
    env:
      - WP_ROOT=/app

  test:api:
    service: appserver
    description: Run API tests
    cmd: bin/test.sh --api
    env:
      - WP_ROOT=/app

  test:admin:
    service: appserver
    description: Run admin tests
    cmd: bin/test.sh --admin
    env:
      - WP_ROOT=/app

  test:core:
    service: appserver
    description: Run core tests
    cmd: bin/test.sh --core
    env:
      - WP_ROOT=/app

  test:coverage:
    service: appserver
    description: Generate code coverage report
    cmd: bin/test.sh --coverage
    env:
      - WP_ROOT=/app
