name: gl-color-palette-generator
recipe: wordpress
config:
  php: '8.3'
  ssl: true
  xdebug: true
  config:
    php: php.ini
  ServerName: gl-color-palette.lndo.site
  database: mysql:8.0
  webroot: .

services:
  appserver:
    config:
      php: php.ini
    composer:
      phpunit/phpunit: '*'
    build:
      - composer install
    run_as_root:
      - touch /tmp/xdebug.log && chmod 666 /tmp/xdebug.log
    overrides:
      environment:
        XDEBUG_MODE: 'debug,develop,trace'
        XDEBUG_CONFIG: 'client_host=host.docker.internal client_port=9003 log=/tmp/xdebug.log'
        WP_TESTS_DIR: /app/wordpress-phpunit
        WP_CORE_DIR: /app/wordpress/
        TEST_DB_NAME: wordpress_test
        TEST_DB_USER: wordpress
        TEST_DB_PASS: wordpress
        TEST_DB_HOST: database
        SIMPLETEST_BASE_URL: 'https://gl-color-palette.lndo.site/'
        BROWSERTEST_OUTPUT_DIRECTORY: /app/sites/simpletest/browser_output

  database:
    type: mysql
    healthcheck: mysql -uroot --silent --execute "SHOW DATABASES;"

tooling:
  composer:
    service: appserver
  phpunit:
    service: appserver
    description: Run PHPUnit tests including browser and javascript tests
    cmd: "/app/vendor/bin/phpunit -c /app/core/phpunit.xml.dist"
  test:
    service: appserver
    description: Run PHPUnit tests
    cmd: composer --working-dir=/app/wp-content/plugins/gl-color-palette-generator test -- $LANDO_TEST_ARGS
  install-wp-tests:
    service: appserver
    description: Install WordPress test suite
    cmd: |
      bash /app/wp-content/plugins/gl-color-palette-generator/bin/install-wp-tests.sh wordpress_test wordpress wordpress database latest true
  install:wordpress:
    service: appserver
    cmd:
      - wp core download && wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database
      - wp core install --url="https://gl-color-palette.lndo.site" --title="GL Color Palette Generator" --admin_user="admin" --admin_password="admin" --admin_email="admin@gl-color-palette.lndo.site"
      - wp plugin install gl-color-palette-generator --activate
